# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from classify import classify


class Ui_mainWindow(object):

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(519, 545)
        mainWindow.setFixedSize(519, 545)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/lenovo/Downloads/icon (2).ico"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(350, 360, 161, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(20)
        self.button.setFont(font)
        self.button.setObjectName("ok_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 20, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 271, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 70, 271, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 651, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 320, 651, 41))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(250, 70, 20, 271))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(310, 120, 191, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.result_0 = QtWidgets.QRadioButton(self.groupBox)
        self.result_0.setGeometry(QtCore.QRect(30, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.result_0.setFont(font)
        self.result_0.setObjectName("result_0")
        self.result_1 = QtWidgets.QRadioButton(self.groupBox)
        self.result_1.setGeometry(QtCore.QRect(30, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.result_1.setFont(font)
        self.result_1.setObjectName("result_1")
        self.result_2 = QtWidgets.QRadioButton(self.groupBox)
        self.result_2.setGeometry(QtCore.QRect(30, 90, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.result_2.setFont(font)
        self.result_2.setObjectName("result_2")
        self.result_3 = QtWidgets.QRadioButton(self.groupBox)
        self.result_3.setGeometry(QtCore.QRect(30, 130, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.result_3.setFont(font)
        self.result_3.setObjectName("result_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 360, 271, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 420, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 110, 211, 211))
        self.groupBox.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.opt_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.opt_3.setGeometry(QtCore.QRect(30, 140, 171, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.opt_3.setFont(font)
        self.opt_3.setObjectName("opt_3")
        self.opt_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.opt_2.setGeometry(QtCore.QRect(30, 100, 171, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.opt_2.setFont(font)
        self.opt_2.setObjectName("opt_2")
        self.opt_1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.opt_1.setGeometry(QtCore.QRect(30, 60, 171, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.opt_1.setFont(font)
        self.opt_1.setObjectName("opt_1")
        self.opt_0 = QtWidgets.QRadioButton(self.groupBox_2)
        self.opt_0.setGeometry(QtCore.QRect(30, 20, 171, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.opt_0.setFont(font)
        self.opt_0.setObjectName("opt_0")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.button.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.label_4.raise_()
        self.lineEdit_2.raise_()
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.button.clicked.connect(self.classification)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "随机分组"))
        self.button.setText(_translate("mainWindow", "生成分组"))
        self.label.setText(_translate("mainWindow", "请输入每组的分组人数:"))
        self.label_2.setText(_translate("mainWindow", "分组算法："))
        self.label_3.setText(_translate("mainWindow", "生成文件选项："))
        self.result_0.setText(_translate("mainWindow", "显示年级"))
        self.result_1.setText(_translate("mainWindow", "显示学院"))
        self.result_2.setText(_translate("mainWindow", "显示班级"))
        self.result_3.setText(_translate("mainWindow", "显示性别"))
        self.label_4.setText(_translate("mainWindow", "请输入生成的文件名称："))
        self.lineEdit_2.setText(_translate("mainWindow", "分组文件"))
        self.opt_3.setText(_translate("mainWindow", "考虑男女比例"))
        self.opt_2.setText(_translate("mainWindow", "考虑院系分布"))
        self.opt_1.setText(_translate("mainWindow", "考虑年级分布"))
        self.opt_0.setText(_translate("mainWindow", "完全随机分组"))

    def classification(self):
        if self.lineEdit.text() == "":
            QtWidgets.QMessageBox.warning(self.button, "警告", "请定义小组人数！")
            return
        choice = -1  # 初始化choice
        if self.opt_0.isChecked():
            choice = 0
        if self.opt_1.isChecked():
            choice = 1
        if self.opt_2.isChecked():
            choice = 2
        if self.opt_3.isChecked():
            choice = 3
        if choice == -1:
            QtWidgets.QMessageBox.warning(self.button, "警告", "请选择分组策略！")
            return
        opt = -1  # 初始化生成选项
        if self.result_0.isChecked():
            opt = 0
        if self.result_1.isChecked():
            opt = 1
        if self.result_2.isChecked():
            opt = 2
        if self.result_3.isChecked():
            opt = 3
        classify.work(choice, self.lineEdit.text(), self.lineEdit_2.text(),
                      opt)
        QtWidgets.QMessageBox.information(self.button, "提示", "成功生成分组文件——%s.xlsx！" % self.lineEdit_2.text())
